import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Date from '../components/date';
import styles from '@/styles/Home.module.css';
import { getSortedPostsData } from '../lib/posts';
import utilStyles from '@/styles/utils.module.css';


export default function Home({ allPostsData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={utilStyles.headingMd}>...</section>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2>Blog</h2>
        <ul className={utilStyles.list}>
          {
            allPostsData.map(({id, date, title}) => (
              <li className={utilStyles.listItem} key={id}>
                <Link href={`/posts/${id}`}>
                  <a>{title}</a>
                </Link>
                <br />
                <small className={utilStyles.lightText}>
                  <Date dateString={date} />
                </small>
              </li>
            ))
          }
        </ul>
      </section>
    </>
  )
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    }
  };
}
